import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  section: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    padding: '40px 16px',
  },
  card: {
    width: '100%',
    maxWidth: '600px',
    background: 'var(--bg-glass)',
    border: '3px solid var(--ink-color)',
    borderRadius: '16px',
    padding: '32px 28px',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    color: 'var(--text-primary)',
    marginBottom: '8px',
    textAlign: 'center',
    fontFamily: 'var(--font-manga)',
    letterSpacing: '0.05em',
  },
  toggleRow: {
    display: 'flex',
    gap: '12px',
    marginBottom: '20px',
    justifyContent: 'center',
  },
  toggleActive: {
    padding: '6px 20px',
    borderRadius: '255px',
    border: '2px solid var(--ink-color)',
    background: 'var(--ink-color)',
    color: 'var(--text-inverse)',
    fontWeight: '700',
    fontSize: '0.95rem',
    cursor: 'pointer',
    transition: 'all 200ms',
    fontFamily: 'inherit',
  },
  toggleInactive: {
    padding: '6px 20px',
    borderRadius: '255px',
    border: '2px solid var(--border-subtle)',
    background: 'transparent',
    color: 'var(--text-muted)',
    fontWeight: '400',
    fontSize: '0.95rem',
    cursor: 'pointer',
    transition: 'all 200ms',
    fontFamily: 'inherit',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    background: 'var(--bg-glass)',
    border: '3px solid var(--border-subtle)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    fontSize: '0.95rem',
    marginBottom: '12px',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    textAlign: 'right',
  },
  textarea: {
    width: '100%',
    minHeight: '130px',
    padding: '14px 16px',
    paddingBottom: '28px',
    background: 'var(--bg-glass)',
    border: '3px solid var(--border-subtle)',
    boxShadow: 'inset 3px 3px 0 rgba(var(--bg-page-rgb), 0.3)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    fontSize: '0.95rem',
    resize: 'vertical',
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    textAlign: 'right',
    lineHeight: '1.6',
    transition: 'all 0.2s ease',
  },
  charCount: {
    position: 'absolute',
    bottom: '10px',
    left: '12px',
    fontSize: '0.75rem',
    transition: 'color 200ms',
    pointerEvents: 'none',
  },
  error: {
    color: 'var(--accent-red)',
    fontSize: '0.85rem',
    marginTop: '6px',
    marginBottom: '0',
    textAlign: 'center',
  },
  sendBtn: {
    width: '100%',
    padding: '14px',
    marginTop: '16px',
    background: 'var(--paper-color)',
    color: 'var(--ink-color)',
    border: '3px solid var(--ink-color)',
    boxShadow: '5px 5px 0 var(--ink-color)',
    borderRadius: '4px',
    fontSize: '1.2rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 200ms',
    fontFamily: 'var(--font-manga)',
    letterSpacing: '0.1em',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '48px',
  },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid rgba(var(--bg-page-rgb), 0.2)',
    borderTopColor: 'var(--ink-color)',
    borderRadius: '50%',
    display: 'inline-block',
    animation: 'spin 0.7s linear infinite',
  },
  successBox: {
    textAlign: 'center',
    padding: '20px 0',
    animation: 'fadeIn 400ms ease',
  },
  successText: {
    fontSize: '1.2rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    marginBottom: '6px',
  },
  successSub: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
  },
  blocked: {
    textAlign: 'center',
    color: 'var(--text-muted)',
    padding: '20px 0',
    fontSize: '0.95rem',
  },
};
